# Generated by Django 2.0 on 2019-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190630_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_order_currency',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='total_ship_currency',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_ship',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
